/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus3

type AzureConnectionXo struct {
	AccountName string `json:"accountName,omitempty"`
	AccountKey string `json:"accountKey,omitempty"`
	ContainerName string `json:"containerName,omitempty"`
	AuthenticationMethod string `json:"authenticationMethod,omitempty"`
}
