/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus3

type AzureBlobStoreApiModel struct {
	// The name of the Azure blob store.
	Name string `json:"name"`
	SoftQuota *BlobStoreApiSoftQuota `json:"softQuota,omitempty"`
	BucketConfiguration *AzureBlobStoreApiBucketConfiguration `json:"bucketConfiguration"`
}
