/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus3

type GenericBlobStoreApiResponse struct {
	SoftQuota *BlobStoreApiSoftQuota `json:"softQuota,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	Unavailable bool `json:"unavailable,omitempty"`
	BlobCount int64 `json:"blobCount,omitempty"`
	TotalSizeInBytes int64 `json:"totalSizeInBytes,omitempty"`
	AvailableSpaceInBytes int64 `json:"availableSpaceInBytes,omitempty"`
}
