/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus3

type ScriptXo struct {
	Name string `json:"name,omitempty"`
	Content string `json:"content,omitempty"`
	Type_ string `json:"type,omitempty"`
}
