/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nexus3

type SupportZipXo struct {
	File string `json:"file,omitempty"`
	Name string `json:"name,omitempty"`
	Size string `json:"size,omitempty"`
	Truncated bool `json:"truncated,omitempty"`
}
