/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IqConnectionXo struct {
	// Whether to use Sonatype Repository Firewall
	Enabled bool `json:"enabled,omitempty"`
	// Show Sonatype Repository Firewall link in Browse menu when server is enabled
	ShowLink bool `json:"showLink,omitempty"`
	// The address of your Sonatype Repository Firewall
	Url string `json:"url,omitempty"`
	// Authentication method
	AuthenticationType string `json:"authenticationType"`
	// User with access to Sonatype Repository Firewall
	Username string `json:"username,omitempty"`
	// Credentials for the Sonatype Repository Firewall User
	Password string `json:"password,omitempty"`
	// Use certificates stored in the Nexus Repository Manager truststore to connect to Sonatype Repository Firewall
	UseTrustStoreForUrl bool `json:"useTrustStoreForUrl,omitempty"`
	// Seconds to wait for activity before stopping and retrying the connection. Leave blank to use the globally defined HTTP timeout.
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
	// Additional properties to configure for Sonatype Repository Firewall
	Properties string `json:"properties,omitempty"`
	// Allow by default when quarantine is enabled and the IQ connection fails
	FailOpenModeEnabled bool `json:"failOpenModeEnabled,omitempty"`
}
