/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AzureBlobStoreApiBucketConfiguration struct {
	// Account name found under Access keys for the storage account.
	AccountName string `json:"accountName"`
	// The name of an existing container to be used for storage.
	ContainerName string `json:"containerName"`
	// The Azure specific authentication details.
	Authentication *AzureBlobStoreApiAuthentication `json:"authentication"`
}
