/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type S3BlobStoreApiBucketConfiguration struct {
	// Details of the S3 bucket such as name and region
	Bucket *S3BlobStoreApiBucket `json:"bucket"`
	// The type of encryption to use if any
	Encryption *S3BlobStoreApiEncryption `json:"encryption,omitempty"`
	// Security details for granting access the S3 API
	BucketSecurity *S3BlobStoreApiBucketSecurity `json:"bucketSecurity,omitempty"`
	// A custom endpoint URL, signer type and whether path style access is enabled
	AdvancedBucketConnection *S3BlobStoreApiAdvancedBucketConnection `json:"advancedBucketConnection,omitempty"`
}
