/*
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.68.1-02
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AzureBlobStoreApiModel struct {
	// The name of the Azure blob store.
	Name string `json:"name"`
	// Settings to control the soft quota.
	SoftQuota *BlobStoreApiSoftQuota `json:"softQuota,omitempty"`
	// The Azure specific configuration details for the Azure object that'll contain the blob store.
	BucketConfiguration *AzureBlobStoreApiBucketConfiguration `json:"bucketConfiguration"`
}
